### ISSUE TITLE
Get some error in Mac 

### ISSUE THREAD

**Issue by Sajibekanti** [1N3/ReverseAPK#4] opened 2018-06-02 06:46 UTC
./install 
                                            
__________                                        
\______   \ _______  __ ___________  ______ ____  
 |       _// __ \  \/ // __ \_  __ \/  ___// __ \ 
 |    |   \  ___/\   /\  ___/|  | \/\___ \  ___/ 
 |____|_  /\___  >\_/  \___  >__|  /____  >\___  >
        \/     \/          \/           \/     \/ 
                                           _____ __________ ____  __.
                                          /  _  \______   \    |/ _|
      --=[( by 1N3@CrowdShield )]=--     /  /_\  \|     ___/      <  
   --=[( https://crowdshield.com )]=--  /    |    \    |   |    |  \ 
                                        \____|__  /____|   |____|__ \
                                                \/                 \/
\e[0m
 Installing reverse-apk...
========================================================= \e[0m
cp: /usr/bin/reverse-apk: Operation not permitted
./install: line 34: apt-get: command not found
fatal: could not create work tree dir '/usr/share/jadx': Operation not permitted
./install: line 36: cd: /usr/share/jadx: No such file or directory
./install: line 37: ./gradlew: No such file or directory
 Done! To use, type reverse-apk <path_to_apk>.

**Comment by 1N3** [comment] 2018-06-02 13:23
Hi, which OS are you running?

It looks like the 'apt-get' command wasn't found which means you're not running Kali Linux/Ubuntu/Debian. I should probably update the README docs to indicate that this script was designed to work on those systems by default...

**Comment by zief** [comment] 2018-10-06 18:28
hahaha... for archlinux you can install jadx and dex2jar using pacman ( official)  but the apktool and other must use community repo

**Comment by 1N3** [comment] 2018-11-08 15:31
Sorry, closing this out. This script unfortunately is not compatible with Mac.

**Closed as completed by 1N3** 2018-11-08 15:31 UTC
